### PR TITLE
Orbital Optimization VQE tutorial

### PR DESCRIPTION
**Pull request by Brogis1**
### Summary

Tutorial for the Orbital Optimization VQE (Hamiltonian basis optimization by orbital rotations added to usual VQE).

### Details and comments

- Notebook shows how to set-up a fast OOVQE calculation in the case of H2.
- Also, the longer H4 calculation is performed that shows an improvement in absolute energy w.r.t. energy computed with standard VQE using paired UCCD ansatz.
- Include @pbark as a Reviewer please.

### CODE REVIEW

**Comment by nonhermitian** [comment]
The H4 cell takes longer than 3 minutes to execute, and is therefore raising an error.

**Comment by Brogis1** [comment]
> The H4 cell takes longer than 3 minutes to execute, and is therefore raising an error.

Thanks, I made it into commented code that the user can run for his/her interest. Hope this is fine.

**Comment by pbark** [comment]
Hi @Brogis1, maybe help the optimizer with a good set off initial values for the optimization to speed it up instead of commenting this out.

**Comment by Brogis1** [comment]
> Hi @Brogis1, maybe help the optimizer with a good set off initial values for the optimization to speed it up instead of commenting this out.

Done. See the latest commit.

**Comment by Eric-Arellano** [comment]
Hi, apologies that this never got merged :/ 

We're moving the qiskit-tutorials repository to live in Qiskit Terra (https://github.com/Qiskit/qiskit-tutorials/issues/1473), so this chemistry-specific tutorial no longer fits into this repository. Instead, it would belong in the Applications projects like Qiskit Nature, but I don't know which it would be? https://qiskit.org/ecosystem/

**Pull request closed without merging**
