### PR TITLE
Update pulse software documentation

### PR DESCRIPTION
**Pull request by lcapelluto**
### Summary

Replace pulse software documentation with the more up to date versions, fixup naming and links, migrate recent changes

### CODE REVIEW

**Comment by nonhermitian** [comment]
Are these still needed given that #989 was merged?  Those said Terra 0.14, but that is not what is about to be released.

**Comment by lcapelluto** [comment]
> Are these still needed given that #989 was merged? Those said Terra 0.14, but that is not what is about to be released.

Yes. These are up to date with 0.15.0. #989 is up to date with 0.14.2. There are some differences between the two.

**Comment by nonhermitian** [comment]
This now has conflicts with the other PR #989  that you made.

**Comment by lcapelluto** [comment]
Conflicts fixed now as promised :)

**Comment by lcapelluto** [comment]
This is no longer blocked by the release, so I'd say it's no longer on hold but ready for merge. However, blocked now on an issue in the ci build to handle pyscf for qiskit chemistry

**Pull request merged**
