### PR TITLE
Algorithm and machine learning tutorials

### PR DESCRIPTION
**Pull request by woodsp-ibm**
This adds a set of new tutorials for Qiskit Aqua `algorithms` and `machine_learning`. The couple of existing files (one in each folder) have been renamed/numbered accordingly with the number prefix.

### CODE REVIEW

**Comment by nonhermitian** [comment]
The new directories need to be added to the directory structure of the docs.

**Comment by woodsp-ibm** [comment]
Ok, done, I had not noticed the index.rst in the root here - I had seen the one on qiskit repo. Is the latter one automatically updated based on this from here?

**Comment by nonhermitian** [comment]
It is not. That will need to be tweaked as well once this gets merged

**Review by nonhermitian — APPROVED** [review]
Looks good.  Thanks.  I will add the needed dirs to the meta.

**Pull request merged**
