### PR TITLE
Community notebook for Quantum Volume

### PR DESCRIPTION
**Pull request by ShellyGarion**
### Summary
Add community notebook for quantum volume
See: 
https://github.com/Qiskit/qiskit-ignis/issues/187

### CODE REVIEW

**Comment by dcmckayibm** [comment]
Looks fine so far

**Comment by rraymondhp** [comment]
Hi, great job!
I was thinking of a similar tutorial after reading the paper, but you got it first.
Just some comment:
1. Are you going to push first and then complete the `TBD` part? I wonder if introduction can be written more to give some abstract. 
2. Can we end the notebook showing the number of quantum volume, say, for a hypothetical small device with some errors set from the noise parameters? It will be nice to conclude showing the result of quantum volume computation.

**Comment by ShellyGarion** [comment]
Thanks for the comments! This is a work in progress [WIP] and it will be merged only after it will be completed and properly reviewed. I uploaded a preliminary version in order to get some feedback, and will continue to work on it in the spirit of your suggestions.

**Comment by ShellyGarion** [comment]
@rraymondhp - do you have any further comments or additions to this tutorial?
@dcmckayibm - could you please review the tutorial?

**Comment by nonhermitian** [comment]
I am confused by this:
```
qubit_lists = [[0,1,3],[0,1,3,5],[0,1,3,5,7],[0,1,3,5,7,10]]
```
why are all odd qubits being picked for a simulator that has all-to-all connectivity?

**Comment by ShellyGarion** [comment]
I took the parameters from the QV notebook in ignis: 
https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/ignis/quantum_volume.ipynb

**Comment by nonhermitian** [comment]
`print(qv_circs_nomeas[0][0])` gives:

```python
(<qiskit.extensions.standard.u3.U3Gate object at 0x1a266c16a0>, [Qubit(QuantumRegister(4, 'qr'), 0)], [])

```
for me.  Also, I do not see where `from IPython import display` is used?

**Comment by aasfaw** [comment]
Hi @ShellyGarion can you please remove the lines `from IPython import display` and `import qiskit`? I verified that you can run the notebook just fine without them.

**Comment by aasfaw** [comment]
@nonhermitian the print statement outputs a text-based circuit for me (partial screenshot below). Any idea what might be happening? I removed the `from IPython import display` and `import qiskit` lines before running.

My `qiskit.__qiskit_version__` is:
```
{'qiskit': '0.10.0',
 'qiskit-terra': '0.8.0',
 'qiskit-ignis': '0.1.1',
 'qiskit-aer': '0.2.0',
 'qiskit-ibmq-provider': '0.2.1',
 'qiskit-aqua': '0.5.0'}
```
screenshot

**Comment by ShellyGarion** [comment]
I removed: `from IPython import display` , but I had to keep `import qiskit` (otherwise I got an error)

**Pull request merged**
