### PR TITLE
Resolved deprecation warnings in transpiler tutorial notebook

### PR DESCRIPTION
**Pull request by wagnersj**
### Summary

Resolved deprecation warnings in issue #990 related to changes in `qiskit-terra` v0.14.0 were appearing in the transpiler tutorial notebook. 

### Details and comments

Resolved `qiskit.extensions.standard` library deprecations by using `qiskit.circuit.library.standard_gates` library instead.

Resolved deprecated function calls in 'DAGCircuit` and `Layout` classes from the `BasicSwap` class defined in the notebook. Basically, a cut-and-paste from the `qiskit.transpiler.passes.BasicSwap`.

Also added some helpful documentation in the Introduction section about installing `pydot` and `graphviz`, which are needed for `dag_drawer`.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
I think #933 was done to update these notebooks but seems not yet to have been merged

**Comment by wagnersj** [comment]
@woodsp-ibm Ah, I see #933. Sorry! Will remove my pull request.

**Comment by wagnersj** [comment]
Closed wrong PR

**Review by nonhermitian — DISMISSED** [review]
Many thanks for this!

**Comment by nonhermitian** [comment]
Actually just need the conflict merged a ready to go.

**Pull request merged**
