### PR TITLE
Add process fidelity

### PR DESCRIPTION
**Pull request by quantumjim**
### Summary
As well as calculating fidelity using `state_fidelity`, the calculation is also done with `process_fidelity`.

### CODE REVIEW

**Comment by quantumjim** [comment]
Done to answer [this question](https://quantumcomputing.stackexchange.com/questions/6326/how-to-calculate-the-fidelity-of-a-certain-gate-of-a-ibmq-device-in-qiskit-using), after discussion with @dcmckayibm and @chriseclectic.

**Comment by dcmckayibm** [comment]
If you run it, it gives the same answer as before?

**Comment by quantumjim** [comment]
The state fidelities are still in there and give answers that are close to those before. I'd say they are the same, within the bounds of the statistics.

The process fidelities are similar but distinct.

**Comment by dcmckayibm** [comment]
The 2Q examples, the state needs be divided by 4

**Comment by quantumjim** [comment]
Good catch. Fixed!

**Pull request merged**
