### PR TITLE
add widget notebook

### PR DESCRIPTION
**Pull request by abbycross**
### Summary

Composer Widget notebook

### Details and comments

I named it 1a so that it falls after the first notebook in the Circuits folder. Is there a better place for it?

### CODE REVIEW

**Comment by abbycross** [comment]
FYI @beckykd

**Comment by nonhermitian** [comment]
The tutorials cannot access the IQX as we want to minimize any blockers due to API issues.

**Comment by abbycross** [comment]
@nonhermitian Better to turn this into a purely text document and post in the doc repo, or to change it to pure markdown within this current file so that it doesn't call IQX, and upload it here?

**Comment by nonhermitian** [comment]
Let me play with this a bit first to see what happens when I try to build it into some docs.

**Comment by raulotaolea** [comment]
@abbycross @nonhermitian The IQX widget library comes pre-installed in the IQX Jupyter Notebook, but it is not available in a public package manager yet. So notebooks outside IQX will not be able to use it.

**Comment by nonhermitian** [comment]
Ok, then will close this for now till the time comes.

**Pull request closed without merging**
