### PR TITLE
Add pulse gates documentation

### PR DESCRIPTION
**Pull request by lcapelluto**
### Summary

 - Add pulse gates documentation
 - Consolidate getting_started, build_instructions, build_schedules pages -> 06_build_schedules
    - Update to use the pulse builder instead of working directly with `Schedule`
    - Add section on basic Pulse Builder usage
 - Remove measurement page
 - Update scheduler (should use calibrations rather than scheduling with inst_map)
 - reindex file names

### Details and comments

This should be released once Pulse gates are in production

### CODE REVIEW

**Comment by divshacker** [comment]
Hey Can you specify which files you have edited @lcapelluto Because I think you have editied some old files . May You please check That you have edited the latest updated files or not . 
Thank You

**Comment by lcapelluto** [comment]
It seems like you deleted and then re-added the same files so now there are awkward merge conflicts.

**Comment by lcapelluto** [comment]
I'm going to update my commit history to help improve the diff (regarding renamed files)

**Comment by lcapelluto** [comment]
https://github.com/Qiskit/qiskit-tutorials/pull/1115/files

**Pull request closed without merging**
