### PR TITLE
Update RB notebooks

### PR DESCRIPTION
**Pull request by ShellyGarion**
### Summary
Updating RB tutorials following API changes in ignis.

### Details and comments
https://github.com/Qiskit/qiskit-ignis/issues/334

### CODE REVIEW

**Comment by nkanazawa1989** [comment]
LGTM. just one small comment

the description above cell 14 should be updated because it doesn't take qobj.
> The function gates_per_clifford takes a compiled qobj and outputs the number of basis gates in each circuit.

**Comment by nonhermitian** [comment]
Note that all the tutorials now go in the Qiskit documentation: https://github.com/Qiskit/qiskit

**Comment by ShellyGarion** [comment]
> 
> 
> Note that all the tutorials now go in the Qiskit documentation: https://github.com/Qiskit/qiskit

Thanks, so I'll close this PR when I will open a new one in the right place.

**Comment by ShellyGarion** [comment]
@nkanazawa1989 - could you please review the updated notebook? 
when it's done, then I'll close this PR and move the notebook to qiskit docs.

**Comment by nkanazawa1989** [comment]
looks good. one minor suggestion: cell 14 can be simplified
```python
for basis_gate in basis_gates:
    print("Number of %s gates per Clifford: %f "%(basis_gate ,
                                                  np.mean([gates_per_cliff[0][basis_gate],
                                                           gates_per_cliff[2][basis_gate]])))
```
because `gates_per_cliff` is dictionary.

and the PR should be on hold until ignis 0.3 is released.

**Comment by ShellyGarion** [comment]
Opened a new PR in qiskit docs: https://github.com/Qiskit/qiskit/pull/866

**Comment by ShellyGarion** [comment]
Fix #892.

**Comment by ShellyGarion** [comment]
Closing since notebook 5a was moved to 4, and 5d was removed.

**Pull request closed without merging**
