### PR TITLE
Fixed Broken Links for some tutorials

### PR DESCRIPTION
**Pull request by divshacker**
All things are done 

### Summary
This PR is clearly the solution of #1108 and #1110 in which there is a problem in loading the links . I have corrected that and made that to the write path. I have uploaded the edited jupyter file not edited the code Please forgive that,

### Details and comments
All details can be found in #1108 and #1110

### CODE REVIEW

**Comment by divshacker** [comment]
Have a look at this @nonhermitian and Let me know if any edit is needed

**Comment by divshacker** [comment]
@SooluThomas @nonhermitian  Are you guys Checking it

**Comment by SooluThomas** [comment]
@divshacker Yes, I'll try to check this PR out after reviewing some of the older PRs. Thanks for your contribution

**Review by SooluThomas — APPROVED** [review]
LGTM!

**Pull request merged**
