### PR TITLE
Removing `%matplotlib inline` from different tutorials 

### PR DESCRIPTION
**Pull request by divshacker**
### Summary
fixes Qiskit/qiskit#1265
#1201 

### Details and comments
All details of this PR can be found in above linked issue

### CODE REVIEW

**Comment by divshacker** [comment]
Done! all the `%matplotlib inline` removed.  @SooluThomas Please check and let me know

**Comment by singhmeet11** [comment]
There were a few tutorials which were actually not using `.draw('mpl')` but had `%matplotlib inline`, @divshacker and I actually removed these ones too after having a discussion.\
**Reason** - As soon as someone would add matplot lib images, they would start to double up creating a sort of mess. This won't happen now.

**Comment by divshacker** [comment]
> There were a few tutorials which were actually not using `.draw('mpl')` but had `%matplotlib inline`, @divshacker and I actually removed these ones too after having a discussion.
> **Reason** - As soon as someone would add matplot lib images, they would start to double up creating a sort of mess. This won't happen now.

Exactly! Also if one runs the `draw()` without `mpl` option or `%matplotlib inline` the figure produced by default is `mpl` only. (If we install the correct and ideal qiskit environment eg. IBM quantum lab which have all things preinstalled).

**Review by SooluThomas — APPROVED** [review]
LGTM

**Pull request merged**
