### PR TITLE
Improves Grover's Algorithm tutorials

### LINKED ISSUE #1407: Improve Grover's algorithm and amplitude amplification tutorial if needed
Part of Qiskit/qiskit-tutorials#1401

### PR DESCRIPTION
**Pull request by divshacker**
### Summary
This PR will Improve [tutorials/algorithms/06_grover](https://qiskit.org/documentation/tutorials/algorithms/06_grover.html) 

### Details and comments
fixes #1407
Part of #1401

### CODE REVIEW

**Review by Eric-Arellano — COMMENTED** [review]
How come all the diagrams changed? Should this PR only fix the deprecated link to the textbook?

**Comment by divshacker** [comment]
> How come all the diagrams changed? Should this PR only fix the deprecated link to the textbook?
I have reran all the cells in my local machine so that would have changed all the diagrams into SVGs. That won't be a problem. Look at this comment to get more context. 
https://github.com/Qiskit/qiskit-tutorials/pull/1446#issuecomment-1528786073

**Comment by divshacker** [comment]
This PR is ready for Review

**Review by frankharkins — APPROVED** [review]
Thank you!

**Review by Eric-Arellano — APPROVED** [review]

**Pull request merged**
