### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by mtreinish**
This commit adds the CI configuration for running sphinx builds in CI.

### CODE REVIEW

**Comment by mtreinish** [comment]
@nonhermitian do the docs build locally for you? Right now this is failing on CPLEX not being installed for aqua:

https://dev.azure.com/qiskit-ci/qiskit-tutorials/_build/results?buildId=13247&view=logs&jobId=1ebc38c8-fade-5a89-24da-f796855a97f6&j=1ebc38c8-fade-5a89-24da-f796855a97f6&t=6e37f2e1-4361-5162-6edc-6531d2c9197a

It's honestly a bit too heavyweight to do that in CI: https://github.com/Qiskit/qiskit-aqua/blob/master/qiskit/aqua/algorithms/minimum_eigen_solvers/cplex/__init__.py#L16

**Comment by nonhermitian** [comment]
Many thanks for doing this. Yeah it does work, but not the latest from pip. Only the previous one 12.10.0. did.  It is causing more than a few headaches.

**Comment by mtreinish** [comment]
The fix for the terra bug which https://github.com/Qiskit/qiskit-tutorials/pull/894/commits/db28762643e37961bbc06e11e3a10f68e8694efb works around is: https://github.com/Qiskit/qiskit-terra/pull/4389 but that will need to be included in a release before this can be reverted.

**Comment by nonhermitian** [comment]
Perhaps we just remove the Latex drawing example for now?

**Comment by mtreinish** [comment]
Yeah, that might be best. Even if I can get it working (which I was pretty sure I did the last time I setup CI around tutorials) the installation of texlive takes a long time because it's so big, several gigabytes. Which can make the CI runs needlessly long depending on networking of the azure node.

**Comment by nonhermitian** [comment]
@mtreinish all the latex code should now be gone.

**Comment by mtreinish** [comment]
ok, I've rebased this and removed the latex install bits. Lets see if this can successfully execute all the tutorials now

**Comment by mtreinish** [comment]
Ugh, more cplex in: https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/aqua/optimization/2_converters_for_quadratic_programs.ipynb should I just delete the last 2 sections there or move it to legacy so we don't try to run it?

**Comment by nonhermitian** [comment]
Just remove it. Once CI is up and running I will tell them to come back and clean

**Comment by nonhermitian** [comment]
Arg. Another one uses cplex and not just docplex?

**Comment by nonhermitian** [comment]
Holy moly it works.

**Comment by mtreinish** [comment]
I just added the azure ci to the branch protection rule, it is now required to pass for changes to master

**Comment by nonhermitian** [comment]
You the man.

**Pull request merged**
