### PR TITLE
Fixed a Old refrence Link in "Examples_vehicle_routing" Tutorial

### PR DESCRIPTION
**Pull request by divshacker**
### Summary
This PR is made to fix the old link that was there in the Refrence section of the "7_examples_vehicle_routing.ipynb" tutorial in Optimization section . 

### Details and comments
It is now connected or reffered to the correct file in the Notebook . 
Please Have a look and let me know if any changes to be done in this PR. 
Thank You

### CODE REVIEW

**Comment by divshacker** [comment]
@SooluThomas  @nonhermitian  Please have a look on one more Fix

**Review by SooluThomas — APPROVED** [review]
LGTM!

**Comment by divshacker** [comment]
I think this is not getting passed or something wrong happend . @SooluThomas  please look into it . I think restarting the tests can work

**Comment by divshacker** [comment]
@SooluThomas
I think it is not automatically merged XD maybe because you have started the test again . Can you please merge it . 
Thank You

**Pull request merged**
