### PR TITLE
Adding README and exercises to qiskit/terra

### PR DESCRIPTION
**Pull request by rraymondhp**
Adding README to explain what each notebook is about. 
Adding exercises to introduce some basic concepts of quantum circuits.

### CODE REVIEW

**Comment by jaygambetta** [comment]
i think these should go in the community folders.

**Comment by rraymondhp** [comment]
Jay, I was thinking of writing exercises corresponding to notebooks at each subdirectory. I thought it would be easier for users to look for hints if each exercise placed under the same subdirectory. What do you suggest? If we place exercises under community, I wonder if they should be under a single subdirectory dedicated to exercises.

**Comment by jaygambetta** [comment]
I think this is a good idea to have an exercise. For the qiskit directory, i want it to autogenerate into the documentation.

**Comment by rraymondhp** [comment]
To clarify, README.md will be autogenerated from `index.ipynb`? 
I think we need a guide (README.md or index.ipynb) about how to traverse in sequence notebooks at each subdirectory. 

It is not trivial where to start when we visit the subdirectory qiskit/terra, for example: 
https://github.com/Qiskit/qiskit-tutorials/tree/master/qiskit/terra

**Pull request closed without merging**
