### PR TITLE
fix qgans

### LINKED ISSUE #1070: QGans QML Notebook doesn't Open
### Information

- **Qiskit version**: N/A (0.23.0)
- **Python version**: N/A (3.8.5)
- **Operating system**: N/A (OSX)

### What is the current behavior?
The [qgans qml tutorial notebook](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/machine_learning/qgans_for_loading_random_distributions.ipynb) doesn't open on github, or iqx, or locally:
Screen Shot 2020-11-02 at 10 51 27 am
Screen Shot 2020-11-02 at 10 51 39 am

### Steps to reproduce the problem
Tried multiple times.

### What is the expected behavior?
Notebook opens and runs.

### Suggested solutions
Fix notebook

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
fixes #1070 

### Details and comments

It seems like there was some git merge conflict data in there that was making it not valid json.  Not sure why the testing still passed.

### CODE REVIEW

**Comment by nonhermitian** [comment]
@Zoufalc This now fails with:

```
AttributeError: 'TwoLocal' object has no attribute 'params'
AttributeError: 'TwoLocal' object has no attribute 'params'
```

I believe this was failing before, but the git commit stuff was masking the failure.

**Comment by nonhermitian** [comment]
@Zoufalc @stefan-woerner any word on getting this fixed?  I believe there is quite a bit of interest in seeing a working version of this notebook.

**Comment by Zoufalc** [comment]
I will take a look right away. Thanks for the reminder.

**Comment by Zoufalc** [comment]
This error is due to some recent changes in the qGAN code in Aqua. I will fix it right away.

**Pull request merged**
