### PR TITLE
Improves 03_vqe_simulation_with_noise

### LINKED ISSUE #1404: Improve VQE on Aer simulator with noise tutorial if needed
Part of Qiskit/qiskit-tutorials#1401

### PR DESCRIPTION
**Pull request by divshacker**
### Summary
This PR will Improve [03_vqe_simulation_with_noise](https://qiskit.org/documentation/tutorials/algorithms/03_vqe_simulation_with_noise.html)

### Details and comments
fixes #1404 
Part of #1401

### CODE REVIEW

**Comment by divshacker** [comment]
Screenshot from 2023-06-04 02-56-28
This code was intentional, or do I update it ? @woodsp-ibm @HuangJunye 
Asking because this tutorial already have Qiskit primitives and updated functions. So It might be left out intentionally? If There is anything like that please let me know 
Thanks

**Comment by divshacker** [comment]
Till now 
I have updated a few broken links and added some more links to predefined functions. 
Also, all the images are converted to SVGs.

**Comment by woodsp-ibm** [comment]
> This code was intentional, or do I update it ?

It needs updating - it should have been when algorithms were switched to primitives but seems to have been an oversight. See #1456

**Review by Eric-Arellano — COMMENTED** [review]
Thanks! Were the figure changes intentional?

**Comment by divshacker** [comment]
> Thanks! Were the figure changes intentional?

No they were not intentional, but it was by default. There won't be any problem as SVG diagrams are better than existing PNG one.

**Comment by divshacker** [comment]
This PR is ready for review.
Thanks

**Review by frankharkins — APPROVED** [review]
Links work and this runs correctly for me, thanks :)

**Review by Eric-Arellano — APPROVED** [review]

**Pull request merged**
