### PR TITLE
Deleted 08_factorizers.ipynb.

### PR DESCRIPTION
**Pull request by dlasecki**
### Summary

This PR deletes a tutorial involving features recently removed from Qiskit Terra algorithms.

### Details and comments

Closes: #1366.

### CODE REVIEW

**Comment by Cryoris** [comment]
This should probably also include renaming of the tutorials after "08" 🙂

**Comment by woodsp-ibm** [comment]
For the renaming (renumbering) it did not really matter - they are just ordered by names and if there was some numeric "hole" the order would still be fine. This is now renaming the tutorial that is being updated in #1369 under its former name.

**Comment by woodsp-ibm** [comment]
Can we drop the renaming of the other tutorial (the 09 one) from this PR and make it independent - otherwise we have to coordinate this with #1369.

**Comment by dlasecki** [comment]
> Can we drop the renaming of the other tutorial (the 09 one) from this PR and make it independent - otherwise we have to coordinate this with #1369.

Done.

**Review by woodsp-ibm — APPROVED** [review]

**Comment by HuangJunye** [comment]
I was not aware of the deprecation. Adding the relevant PR and issues here
- https://github.com/Qiskit/qiskit-terra/issues/8503
- https://github.com/Qiskit/qiskit-terra/pull/8617

**Comment by HuangJunye** [comment]
We were thinking about [adding deprecation for tutorials](https://github.com/Qiskit/qiskit-tutorials/pull/1353) as well but we haven't implemented it yet. Perhaps this would be a good one to test as well. @SooluThomas What do you think?

I think the message can be similar to [the deprecation message of the Shor class](https://github.com/Qiskit/qiskit-terra/pull/8699), direct people to the textbook chapter.

**Comment by ElePT** [comment]
Hi!! @HuangJunye, is there any update on the deprecation of this tutorial? Let me know if there's anything I can help with.

**Comment by HuangJunye** [comment]
@ElePT https://github.com/Qiskit/qiskit/pull/1655 will add the redirects to the textbook chapter. After it's merged we can merge this one.

**Comment by ElePT** [comment]
> 

Thank you!

**Comment by HuangJunye** [comment]
https://github.com/Qiskit/qiskit/pull/1655 is merged and the redirect is working as intended.

**Review by HuangJunye — APPROVED** [review]

**Pull request merged**
