### PR TITLE
New basic notebooks

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
Updated basic notebooks and removed ones where there was overlap with other resources

### CODE REVIEW

**Comment by jaygambetta** [comment]
I would not remove the ibm_q_provider as this should become the place for the provider doc

**Comment by nonhermitian** [comment]
Ok images have been fixed.  Turns out not all `` functionality is supported, and must use `style`.

**Comment by nonhermitian** [comment]
@jaygambetta The notebook has been returned, but renamed to IBMQ Account since that is now what the `IBMQ` object is called.

**Comment by jaygambetta** [comment]
great.

**Pull request merged**
