### PR TITLE
Fix too many `index.rst` problem (#1315)

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
Closes https://github.com/Qiskit/qiskit-tutorials/issues/1315. As explained there, these `index.rst` pages result in our Tutorials home page having extra entries that simply link to that section's other entries.

This PR fixes it by mirroring `tutorials.rst` from `qiskit-metapackage`. Our `index.html` now directly calls `nbgallery` with `glob`, rather than referring to `index.rst` using normal Sphinx mechanisms. That results in this tutorials repo rendering like this:

Screenshot 2023-07-11 at 9 54 04 AM

The metapackage ignores this repo's `index.rst` and only copies over the `tutorials/` folder. So, it will copy over the same content as before, only now without the `index.rst` files in each subfolder.

### CODE REVIEW

**Comment by HuangJunye** [comment]
Thanks for your contributions. I need to do a local build to see if removing the index pages is indeed the right approach. The qiskit documentation building is a bit complicated. I think the index page might still be useful when the tutorials are built on its own. An alternative approach is to ignore the index page in the qiskit meta package.

**Comment by SaumyaBhushan** [comment]
Sure @HuangJunye

**Comment by HuangJunye** [comment]
Closing this PR because qiskit-tutorials content is going to be migrated to qiskit-terra: https://github.com/Qiskit/qiskit-tutorials/issues/1473 Thanks a lot for your interest in contributing all the same!

**Comment by Eric-Arellano** [comment]
> Closing this PR because qiskit-tutorials content is going to be migrated to qiskit-terra: https://github.com/Qiskit/qiskit-tutorials/issues/1473 Thanks a lot for your interest in contributing all the same!

Actually, no, let's keep this open! I was today going to try making this same page because this is an annoying issue in the metapackage and fixing this will help in the metapackage migration. I didn't realize this was already open!

Thank you @SaumyaBhushan and pardon how long it took for a review. I will try this out locally today and merge once confirmed it works how we want.

**Review by javabster — APPROVED** [review]
LGTM 🚀

**Pull request merged**
