### PR TITLE
Fixed a notebook

### LINKED ISSUE #1167: tcirc not used
### Informations

- **Qiskit version**: 0.25.0
- **Python version**: 3.8.9 (default, Apr 8 2021, 12:01:33) [GCC 9.3.0]
- **Operating system**: Linux

### What is the current behavior?
https://qiskit.org/documentation/tutorials/simulators/7_matrix_product_state_method.html

### Steps to reproduce the problem
Run find tcirc. We can see 3 lines: `tcirc = transpile(circ, simulator)`
tcirc is never used.

### What is the expected behavior?
No unused variables.

### Suggested solutions
Probably on the next line the simulator should run the transpiled circuit: 
`result = simulator.run(tcirc).result()`

### PR DESCRIPTION
**Pull request by divshacker**
### Summary
fixes #1167

### CODE REVIEW

**Comment by divshacker** [comment]
Hey @SooluThomas  and @iuliazidaru check this PR and let me know If any further changes required

**Comment by iuliazidaru** [comment]
Looks good to me. Not sure about the ownership and if it is enough that I review and approve...

**Comment by divshacker** [comment]
> Looks good to me. Not sure about the ownership and if it is enough that I review and approve...

I have tested the code and it is working fine after applying your fix. I am sure your fix is correct. But I don't know if it is good in approving this PR. Hey @nonhermitian can you please look into this. Thanks

**Comment by divshacker** [comment]
Hey @SooluThomas @nonhermitian  Please review this PR and let me know If any changes required or not.
Thank You

**Review by SooluThomas — APPROVED** [review]

**Pull request merged**
