### PR TITLE
Add mergify configuration

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

This adds a simple Mergify configuration that will automerge PRs if the `automerge` label is applied to them, they've passed their tests and are approved by somebody with write access.  We still need to enable the Mergify bot on this repository from its control panel before anything will happen.

### CODE REVIEW

**Review by HuangJunye — APPROVED** [review]
Thanks a lot!

**Comment by jakelishman** [comment]
It's worth holding off on merging this until the Mergify bot is enabled for the repository - it'll lint the rules for us and tell us if there are problems, even before the merge, once it's enabled.

I don't have write access on this repository, so I can't create the `automerge` label myself, but you should be able to.  The label doesn't need to be anything special, just to have the exact same name.  The description and colour can be anything (though for consistency, Terra has a white `automerge`).

**Comment by HuangJunye** [comment]
Thank you for the explanations! I added the `automerge` label. For getting mergify bot enabled. Should I ping Matthew?

**Comment by jakelishman** [comment]
No need to ping him, I'd think - he'll see the conversation on Slack when he comes online in a couple of hours' time.

**Pull request merged**
