### PR TITLE
Single and multi-qubit SWAP test tutorial

### LINKED ISSUE #1228: SWAP test tutorial
### What is the expected behavior?
SWAP test is a classic example in quantum computing which can be used as base to example various functionalities in qiskit. I would like to contribute a tutorial with visuals on bloch sphere on how we can use qiskit to find how much do two states differ.

### PR DESCRIPTION
**Pull request by darshkaushik**
### Summary
This is a tutorial on SWAP test that might help users to understand how the SWAP test works and how it could be generalized to N-qubits

### Details and comments
This is to fix #1228

### CODE REVIEW

**Comment by darshkaushik** [comment]
This is to fix #1228

**Comment by darshkaushik** [comment]
@woodsp-ibm can you please help out here

**Comment by woodsp-ibm** [comment]
If I look in the error log from the build it has this
```
Notebook error:
NoSuchKernel in tutorials/algorithms/09_swap_test.ipynb:
No such kernel named qiskitml
```
But I see now from your issue you already have seen that. It relates to this in the notebook at the end from the kernel setting
```
  "kernelspec": {
   "display_name": "qiskitml",
   "language": "python",
   "name": "qiskitml"
  },
```
If you look at other notebooks here (view Raw) they look like
```
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
```  
So if you can switch the kernel to `python3` which I think is the default, then it should run here too I think

Now the `algorithms` folder here is intended as a learning path for the code in qiskit.algorithms. I know @nonhermitian created a new category `textbook` that is more geared towards say textbook algorithms etc - maybe this is better placed there.

**Comment by darshkaushik** [comment]
@woodsp-ibm it worked, thanks a ton. @nonhermitian I have added a copy of this tutorial in textbook section too as suggested. 

Hoping to get a review.

**Comment by darshkaushik** [comment]
@woodsp-ibm can you give this a review

**Comment by Eric-Arellano** [comment]
Hi, pardon that this never got a final review :/ Thank you for making Qiskit better!

We're very soon archiving the qiskit-tutorials repository to simplify how we build our documentation. The tutorials will be built directly in https://github.com/Qiskit/qiskit-terra and algorithms related ones in https://github.com/qiskit-community/qiskit-algorithms.

If you'd still be interested in landing this, it'd be best to open up a new PR in qiskit-algorithms. They're setting up the tutorial infrastructure this week.

I unfortunately can't comment on whether the PR would be accepted or not because I don't know the underlying content well enough. But the repo is more actively maintained so should get a response, and I can help ping the relevant people if you haven't heard back.

Again, sorry for us not reviewing this earlier!

**Pull request closed without merging**
