### PR TITLE
Updated a broken Link in 08_fixed_income_pricing.ipynb

### PR DESCRIPTION
**Pull request by divshacker**
### Summary
There is a broken link (which shows PAGE NOT FOUND) in the tutorial [08_fixed_income_pricing](https://qiskit.org/documentation/tutorials/finance/08_fixed_income_pricing.html)
I have fixed that by correcting that link to the correct file . 

### Details and comments
Please let me know if any changes is needed . 
Thank You

### CODE REVIEW

**Comment by divshacker** [comment]
@SooluThomas @nonhermitian  Please have a look and let me know that 
Thank You

**Comment by SooluThomas** [comment]
@divshacker Can you please install the latest Qiskit version 0.23.3, run the cells and push again?

**Comment by divshacker** [comment]
Sure I will....

**Comment by divshacker** [comment]
@SooluThomas check Now and let me know if any further changes required.

**Review by SooluThomas — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
