### PR TITLE
Update 1_getting_started_with_qiskit.ipynb

### PR DESCRIPTION
**Pull request by ssangskriti**
### Summary
changed \\rho  to $\rho$ in the visualization markdown cell of statevector backend

### Details and comments

ignorable little change

### CODE REVIEW

**Comment by nonhermitian** [comment]
Needs to be changed to `\\rho`:

Screen Shot 2020-07-27 at 10 31 33

**Comment by ssangskriti** [comment]
need this '\rho' to be changed to ρ by '$\rho$' instead of '\\rho' .
image

**Comment by nonhermitian** [comment]
Please check the rendered notebook on GitHub. You will see the error.

**Comment by ssangskriti** [comment]
don't know why GitHub is showing error..but it worked properly on Jupyter notebook and google colab too.
image

**Comment by nonhermitian** [comment]
Yes, this looks to be just a bug on github.

**Pull request merged**
