### PR TITLE
Fixed: Dot product symbol used instead of fullstop (Qiskit/qiskit-aer#883)

### PR DESCRIPTION
**Pull request by TanveshT**
### Summary
An issue was raised under the [qiskit-aer](https://github.com/Qiskit/qiskit-aer) package regarding this and I fixed it over here. The issue can be seen [here](https://github.com/Qiskit/qiskit-aer/issues/883)

### Details and comments

There were full stops used instead of dot product symbols so the necessary change has been made.

### CODE REVIEW

**Comment by TanveshT** [comment]
Thanks, @3yakuya Do I need to do anything as it saying the review is still required.

**Comment by 3yakuya** [comment]
Yeah we need somebody with write permissions to this repo to merge. Just has to wait to be picked up

**Comment by TanveshT** [comment]
Okay thank you for responding and reviewing, we'll wait then

**Comment by TanveshT** [comment]
Hey @3yakuya Can you tag someone who has the required permissions for the repo. I know one of them I guess.

@nonhermitian Can you address this PR, even if the issue is closed this PR is still valid.

**Review by nonhermitian — APPROVED** [review]
This looks good.  Thanks for correcting this.

**Comment by TanveshT** [comment]
Thanks @nonhermitian for accepting the PR

**Pull request merged**
