### PR TITLE
Fixed Some Broken Links in "start_here" file

### PR DESCRIPTION
**Pull request by divshacker**
### Summary
This PR is clearly the fix of #1143 . All the Links are fixed now. 

### Details and comments
There were so many links given which are wrong referred but I have edited that and fixed all of them. The changes can be clearly seen in changes section of the file. 
Let me know what else is needed.
Thank you.

### CODE REVIEW

**Comment by divshacker** [comment]
Please review this PR and let me know any changes  @SooluThomas  @nonhermitian @mtreinish 
Thank You

**Comment by divshacker** [comment]
BTW I don't know why it is rendering the wrong numbering. It looks good when it is opened in jupyter but on github it is showing wrong numbering.

**Comment by divshacker** [comment]
hey @SooluThomas @nonhermitian @mtreinish  Can you guys please check this PR

**Review by SooluThomas — APPROVED** [review]
LGTM

**Pull request merged**
